# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-04 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veneers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcblayer',
            name='hardness',
            field=models.CharField(max_length=20, verbose_name='软板/硬板'),
        ),
    ]
