# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veneers', '0002_auto_20200404_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veneer',
            name='chip_model',
            field=models.CharField(max_length=30, verbose_name='芯片型号'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='chip_type',
            field=models.CharField(max_length=30, verbose_name='芯片类型'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='craft',
            field=models.CharField(max_length=30, verbose_name='工艺人员'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='group',
            field=models.CharField(max_length=30, verbose_name='所属组'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='modify_stage',
            field=models.CharField(max_length=30, verbose_name='原理图变更阶段'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='pcb_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='投板编码'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='pcb_model',
            field=models.CharField(max_length=30, verbose_name='单板形态'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='pcb_name',
            field=models.CharField(max_length=30, verbose_name='单板名称'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='pcb_procedure',
            field=models.CharField(max_length=30, verbose_name='投板流程'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='pcb_type',
            field=models.CharField(max_length=30, verbose_name='单板类型'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='project',
            field=models.CharField(max_length=30, verbose_name='版本/技术项目'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='qa',
            field=models.CharField(max_length=30, verbose_name='QA人员'),
        ),
        migrations.AlterField(
            model_name='veneer',
            name='sim_req',
            field=models.CharField(max_length=30, verbose_name='仿真需求'),
        ),
    ]
