# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-04 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veneers', '0003_auto_20200404_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veneer',
            name='schedule',
            field=models.IntegerField(default=0, verbose_name='进度'),
        ),
    ]
