# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-04 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veneers', '0005_auto_20200405_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veneer',
            name='pcb_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='veneers.PCBLayer', verbose_name='单板层阶'),
        ),
    ]
