# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-05 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='assign_veneer',
        ),
    ]
