# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-05 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_auto_20200405_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='admin_menu',
        ),
    ]
