# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-05 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_remove_permission_admin_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_active',
        ),
    ]
