# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-06 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_remove_permission_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='permissions.Permission', verbose_name='拥有权限'),
        ),
    ]
