# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-06 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_auto_20200406_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='permission',
            name='roles',
            field=models.ManyToManyField(related_name='permissions', to='permissions.Role'),
        ),
    ]
