# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-06 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_auto_20200406_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='roles',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='permissions.Permission', verbose_name='拥有权限'),
        ),
    ]
